Move all hardware/amlogic code to C++17
This is required because of the change to StaticString16 to use C++17
features. Explicitly overridding to C++14 will cause a build error like
the following:

vendor/amlogic/common/frameworks/services/remotecontrol/server_main.cpp:24:
frameworks/native/libs/binder/include/binder/IPCThreadState.h:21:
frameworks/native/libs/binder/include/binder/Parcel.h:30:
system/core/libutils/include/utils/String16.h:240:1:
error: C++ requires a type specifier for all declarations
StaticString16(const F&)->StaticString16<sizeof(F) / sizeof(char16_t)>;
^
1 error generated.

Test: make -j rc_server
Test: make -j dist # (franklin)
Change-Id: I82ec9b845ffa337f4dd749ffb046cfc67a493cee